security:
    encoders:
        AppBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       
            - ROLE_USER
            - ROLE_MODERATOR
            - ROLE_SONATA_ADMIN_PLAYER_GAME_RESULT_LIST
            - ROLE_SONATA_ADMIN_PLAYER_GAME_RESULT_CREATE
            - ROLE_SONATA_ADMIN_PLAYER_GAME_RESULT_EDIT
            - ROLE_SONATA_ADMIN_PLAYER_GAME_RESULT_DELETE
            - ROLE_SONATA_ADMIN_TEAM_GAME_RESULT_LIST
            - ROLE_SONATA_ADMIN_TEAM_GAME_RESULT_CREATE
            - ROLE_SONATA_ADMIN_TEAM_GAME_RESULT_EDIT
            - ROLE_SONATA_ADMIN_TEAM_GAME_RESULT_DELETE
            - ROLE_SONATA_ADMIN_TEAMS_LIST
            - ROLE_SONATA_ADMIN_TEAMS_CREATE
            - ROLE_SONATA_ADMIN_TEAMS_EDIT
            - ROLE_SONATA_ADMIN_TEAMS_DELETE
            - ROLE_SONATA_ADMIN_AGE_CATEGORY_LIST
            - ROLE_SONATA_ADMIN_AGE_CATEGORY_CREATE
            - ROLE_SONATA_ADMIN_AGE_CATEGORY_EDIT
            - ROLE_SONATA_ADMIN_AGE_CATEGORY_DELETE
            - ROLE_SONATA_ADMIN_MEMBERSHIP_TYPE_LIST
            - ROLE_SONATA_ADMIN_MEMBERSHIP_TYPE_CREATE
            - ROLE_SONATA_ADMIN_MEMBERSHIP_TYPE_EDIT
            - ROLE_SONATA_ADMIN_MEMBERSHIP_TYPE_DELETE
            - ROLE_SONATA_ADMIN_SEASONS_LIST
            - ROLE_SONATA_ADMIN_SEASONS_CREATE
            - ROLE_SONATA_ADMIN_SEASONS_EDIT
            - ROLE_SONATA_ADMIN_SEASONS_DELETE
            - ROLE_SONATA_ADMIN_TEAM_ROLE_LIST
            - ROLE_SONATA_ADMIN_TEAM_ROLE_CREATE
            - ROLE_SONATA_ADMIN_TEAM_ROLE_EDIT
            - ROLE_SONATA_ADMIN_TEAM_ROLE_DELETE
            - ROLE_SONATA_ADMIN_USERS_MAKE_MODER
        ROLE_MODERATOR:
            - ROLE_SONATA_ADMIN_GAMES_LIST
            - ROLE_SONATA_ADMIN_GAMES_CREATE
            - ROLE_SONATA_ADMIN_GAMES_EDIT
            - ROLE_SONATA_ADMIN_GAMES_DELETE
            - ROLE_SONATA_ADMIN_PLAYERS_LIST
            - ROLE_SONATA_ADMIN_PLAYERS_CREATE
            - ROLE_SONATA_ADMIN_PLAYERS_EDIT
            - ROLE_SONATA_ADMIN_PLAYERS_DELETE
            - ROLE_SONATA_ADMIN_PLAYER_EVENTS_LIST
            - ROLE_SONATA_ADMIN_PLAYER_EVENTS_CREATE
            - ROLE_SONATA_ADMIN_PLAYER_EVENTS_EDIT
            - ROLE_SONATA_ADMIN_PLAYER_EVENTS_DELETE
            - ROLE_SONATA_ADMIN_GAME_EVENTS_LIST
            - ROLE_SONATA_ADMIN_GAME_EVENTS_CREATE
            - ROLE_SONATA_ADMIN_GAME_EVENTS_EDIT
            - ROLE_SONATA_ADMIN_GAME_EVENTS_DELETE
            - ROLE_SONATA_ADMIN_COMMENT_LIST
            - ROLE_SONATA_ADMIN_COMMENT_DELETE
            - ROLE_SONATA_ADMIN_TEAM_PLAYER_ASSOCIATION_LIST
            - ROLE_SONATA_ADMIN_TEAM_PLAYER_ASSOCIATION_CREATE
            - ROLE_SONATA_ADMIN_TEAM_PLAYER_ASSOCIATION_EDIT
            - ROLE_SONATA_ADMIN_TEAM_PLAYER_ASSOCIATION_DELETE
            - ROLE_SONATA_ADMIN_USERS_LIST
            - ROLE_SONATA_ADMIN_USERS_EDIT

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        main:
            entity: { class: AppBundle:User }
        custom_hwi_provider: { id: chgk.oauth.user_provider }

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                login_path:        /login
                use_forward:       false
                failure_path:      /login
                oauth_user_provider:
                    service: chgk.oauth.user_provider
    access_decision_manager:
        strategy: unanimous
            
    access_control:
        - { path: ^/admin, roles: ROLE_MODERATOR }
