security:
    encoders:
        AppBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_MODERATOR
            - ROLE_SONATA_ADMIN_PLAYER_GAME_RESULT_LIST
            - ROLE_SONATA_ADMIN_PLAYER_GAME_RESULT_CREATE
            - ROLE_SONATA_ADMIN_PLAYER_GAME_RESULT_EDIT
            - ROLE_SONATA_ADMIN_PLAYER_GAME_RESULT_DELETE
            - ROLE_SONATA_ADMIN_TEAM_GAME_RESULT_LIST
            - ROLE_SONATA_ADMIN_TEAM_GAME_RESULT_CREATE
            - ROLE_SONATA_ADMIN_TEAM_GAME_RESULT_EDIT
            - ROLE_SONATA_ADMIN_TEAM_GAME_RESULT_DELETE
            - ROLE_SONATA_ADMIN_TEAM_LIST
            - ROLE_SONATA_ADMIN_TEAM_CREATE
            - ROLE_SONATA_ADMIN_TEAM_EDIT
            - ROLE_SONATA_ADMIN_TEAM_DELETE
            - ROLE_SONATA_ADMIN_AGE_CATEGORY_LIST
            - ROLE_SONATA_ADMIN_AGE_CATEGORY_CREATE
            - ROLE_SONATA_ADMIN_AGE_CATEGORY_EDIT
            - ROLE_SONATA_ADMIN_AGE_CATEGORY_DELETE
            - ROLE_SONATA_ADMIN_MEMBERSHIP_TYPE_LIST
            - ROLE_SONATA_ADMIN_MEMBERSHIP_TYPE_CREATE
            - ROLE_SONATA_ADMIN_MEMBERSHIP_TYPE_EDIT
            - ROLE_SONATA_ADMIN_MEMBERSHIP_TYPE_DELETE
            - ROLE_SONATA_ADMIN_SEASON_LIST
            - ROLE_SONATA_ADMIN_SEASON_CREATE
            - ROLE_SONATA_ADMIN_SEASON_EDIT
            - ROLE_SONATA_ADMIN_SEASON_DELETE
            - ROLE_SONATA_ADMIN_TEAM_ROLE_LIST
            - ROLE_SONATA_ADMIN_TEAM_ROLE_CREATE
            - ROLE_SONATA_ADMIN_TEAM_ROLE_EDIT
            - ROLE_SONATA_ADMIN_TEAM_ROLE_DELETE
            - ROLE_SONATA_ADMIN_USER_MAKE_MODER
        ROLE_MODERATOR:
            - ROLE_SONATA_ADMIN_GAME_LIST
            - ROLE_SONATA_ADMIN_GAME_CREATE
            - ROLE_SONATA_ADMIN_GAME_EDIT
            - ROLE_SONATA_ADMIN_GAME_DELETE
            - ROLE_SONATA_ADMIN_PLAYER_LIST
            - ROLE_SONATA_ADMIN_PLAYER_CREATE
            - ROLE_SONATA_ADMIN_PLAYER_EDIT
            - ROLE_SONATA_ADMIN_PLAYER_DELETE
            - ROLE_SONATA_ADMIN_PLAYER_EVENT_LIST
            - ROLE_SONATA_ADMIN_PLAYER_EVENT_CREATE
            - ROLE_SONATA_ADMIN_PLAYER_EVENT_EDIT
            - ROLE_SONATA_ADMIN_PLAYER_EVENT_DELETE
            - ROLE_SONATA_ADMIN_GAME_EVENT_LIST
            - ROLE_SONATA_ADMIN_GAME_EVENT_CREATE
            - ROLE_SONATA_ADMIN_GAME_EVENT_EDIT
            - ROLE_SONATA_ADMIN_GAME_EVENT_DELETE
            - ROLE_SONATA_ADMIN_EVENT_LIST
            - ROLE_SONATA_ADMIN_EVENT_CREATE
            - ROLE_SONATA_ADMIN_EVENT_EDIT
            - ROLE_SONATA_ADMIN_EVENT_DELETE
            - ROLE_SONATA_ADMIN_COMMENT_LIST
            - ROLE_SONATA_ADMIN_COMMENT_DELETE
            - ROLE_SONATA_ADMIN_TEAM_PLAYER_ASSOCIATION_LIST
            - ROLE_SONATA_ADMIN_TEAM_PLAYER_ASSOCIATION_CREATE
            - ROLE_SONATA_ADMIN_TEAM_PLAYER_ASSOCIATION_EDIT
            - ROLE_SONATA_ADMIN_TEAM_PLAYER_ASSOCIATION_DELETE
            - ROLE_SONATA_ADMIN_USER_LIST
            - ROLE_SONATA_ADMIN_USER_EDIT
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_LIST
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_CREATE
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_EDIT
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_DELETE
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_HAS_MEDIA_LIST
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_HAS_MEDIA_CREATE
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_HAS_MEDIA_EDIT
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_HAS_MEDIA_DELETE
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_LIST
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_CREATE
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_EDIT
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_DELETE

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_decision_manager:
        strategy: unanimous

    access_control:
        - { path: ^/admin, roles: ROLE_MODERATOR }
