event:
    type:     rest
    resource: AppBundle\Controller\API\EventsController

opinions:
    type:     rest
    resource: AppBundle\Controller\API\OpinionsController
    
comments:
    type:     rest
    parent:   event
    resource: AppBundle\Controller\API\CommentsController
    
age_categories:
    type:     rest
    resource: AppBundle\Controller\API\AgeCategoriesController
    
games:
    type:     rest
    resource: AppBundle\Controller\API\GamesController
    
game_results:
    type:     rest
    resource: AppBundle\Controller\API\GameResultsController
    
membership_types:
    type:     rest
    resource: AppBundle\Controller\API\MembershipTypesController
