event:
    type:     rest
    resource: AppBundle\Controller\API\EventsController

opinions:
    type:     rest
    resource: AppBundle\Controller\API\OpinionsController
    
comments:
    type:     rest
    parent:   event
    resource: AppBundle\Controller\API\CommentsController
